### ISSUE TITLE
[FEATURE] S3 Transport: clear error message when input does not exist

### ISSUE THREAD

**Issue by gquintana** [elasticsearch-dump/elasticsearch-dump#1045]
**Is your feature request related to a problem? Please describe.**
When restoring data stored in an S3 bucket to Opensearch, when the input file file does not exist an AccessDenied error is raised.

```
elasticdump --input=s3://mybucket/mydump/myindex.mapping.json --output=https://myopensearch.eu-west-1.es.amazonaws.com/myindex --type=mapping

Fri, 23 Aug 2024 12:18:38 GMT | starting dump
AccessDenied: Access Denied
    at Request.extractError (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/services/s3.js:711:35)
    at Request.callListeners (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'AccessDenied',
  region: null,
  time: 2024-08-23T12:18:38.859Z,
  requestId: 'B6B1KDBZ2MEZM70N',
  extendedRequestId: 'FIcKsrZp4OAl5TjfaneIkIdleubqfOWNvPPXCPXlt3Q9MGfrUDS5UiGWmYlis1vwnmFFl4v1V3c=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 12.685616039839775
} Uncaught Exception thrown
```

I took me ages to understand it was not a permission/policy problem, but a stupid typo in the input file name (my bad).
As the error is raised by AWS SDK lib, I ignore whether elasticsearch dump can do something.

**Describe the solution you'd like**
Have a clear error message saying, the S3 file does not exist, instead of this misleading error message.

**Comment by ferronrsmith** [comment]
There is nothing elasticdump can do about this. This is simply the error message that comes back from aws-sdk as you stated. 

I'll tag this as cookbook for future users, thanks.
