### ISSUE TITLE
[BUG] multielasticdump with direction=load does not support filesize and parrams --type

### ISSUE THREAD

**Issue by losyashfuse95** [elasticsearch-dump/elasticsearch-dump#1064]
**Context**
After backing up my data I can't restore it because of a variable filesize 

- ElasticDump version 
Version v6.113.0 in docker
- Elasticsearch version
Version Elasticsearch 7.10.2
- Command to dump
I erased some data for security reasons.
```
docker run --net=host --rm --name="dump" -e NODE_TLS_REJECT_UNAUTHORIZED=0 -i elasticsearch-dump \
                  multielasticdump --direction=dump --limit=8000 \
                  --s3AccessKeyId '{s3AccessKeyId}' \
                  --s3SecretAccessKey '{s3SecretAccessKey}' \
                  --input=https://log:pass@{server}/ \
                  --output "s3://{bucket}/{server}/{index_pattern}" \
                  --s3Region {S3Region} \
                  --s3ForcePathStyle true \
                  --s3Endpoint {s3Endpoint} \
                  --fileSize 4gb \
                  --s3Compress true \
                  --match={index_pattern} --parallel 6 --ignoreChildError true
              
```

After dump I get files in s3
```
3228   s3://<bucket>/<path>/index-creator-2024.11.16.mapping.split-0.json.gz
422   s3://<bucket>/<path>/index-creator-2024.11.16.settings.split-0.json.gz
628529   s3://<bucket>/<path>/index-creator-2024.11.16.split-0.json.gz
48704   s3://<bucket>/<path>/index-creator-2024.11.16.template.split-0.json.gz
```

When I try to recover data with the command:
```
docker run --net=host --rm --name="test" -e NODE_TLS_REJECT_UNAUTHORIZED=0 -i elasticsearch-dump multielasticdump --direction=load --limit=8000 --s3AccessKeyId '' --s3SecretAccessKey ''  --output="https://log:pass@<es_node>:9201" --input "s3://<bucket>/<path>" --match=index-creator-2024.11.16 --fsCompress  --s3Compress --fileSize 4gb --ignoreChildError true
```
I get the following error
```bash
Tue, 19 Nov 2024 08:41:28 GMT | We are performing : load
Tue, 19 Nov 2024 08:41:28 GMT | options: {"debug":true,"parallel":16,"match":"index-creator-2024.11.16","matchType":"alias","order":"asc","input":"s3://<bucket>/<path>","output":"https://log:pass@<es_node>:9201","scrollId":null,"scrollTime":"10m","scroll-with-post":false,"timeout":null,"limit":8000,"offset":0,"size":-1,"direction":"load","support-big-int":false,"big-int-fields":"","ignoreAnalyzer":true,"ignoreChildError":true,"ignoreData":false,"ignoreMapping":false,"ignoreSettings":false,"ignoreTemplate":false,"ignoreAlias":true,"ignoreIndex":true,"ignoreType":[],"includeType":null,"interval":1000,"delete":false,"prefix":"","suffix":"","transform":null,"headers":null,"params":null,"input-params":null,"output-params":null,"searchBody":null,"searchWithTemplate":null,"cert":null,"key":null,"pass":null,"ca":null,"tlsAuth":false,"input-cert":null,"input-key":null,"input-pass":null,"input-ca":null,"output-cert":null,"output-key":null,"output-pass":null,"output-ca":null,"httpAuthFile":null,"concurrency":1,"carryoverConcurrencyCount":true,"intervalCap":5,"concurrencyInterval":5000,"overwrite":false,"fsCompress":true,"compressionLevel":-1,"awsChain":false,"awsAccessKeyId":null,"awsSecretAccessKey":null,"awsIniFileProfile":null,"awsService":null,"awsRegion":null,"awsUrlRegex":null,"fileSize":"-","s3AccessKeyId":"","s3SecretAccessKey":"","s3Region":"ru-moscow-1","s3Endpoint":"","s3SSLEnabled":true,"s3ForcePathStyle":true,"s3Compress":true,"s3ServerSideEncryption":null,"s3SSEKMSKeyId":null,"s3ACL":null,"quiet":false}
(node:7) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
Tue, 19 Nov 2024 08:41:28 GMT | list of indexes["index-creator-2024.11.16.mapping.split-0","index-creator-2024.11.16.settings.split-0","index-creator-2024.11.16.split-0","index-creator-2024.11.16.template.split-0"]
Tue, 19 Nov 2024 08:41:28 GMT | Working on index-creator-2024.11.16.mapping.split-0
Tue, 19 Nov 2024 08:41:28 GMT | indexing template s3://<bucket>/<path>/index-creator-2024.11.16.mapping.split-0.template.json.gz to https://log:pass@<es_node>:9201/index-creator-2024.11.16.mapping.split-0
Tue, 19 Nov 2024 08:41:28 GMT [debug] | fork: /usr/local/lib/node_modules/elasticdump/bin/elasticdump --type=template,--input=s3://<bucket>/<path>/index-creator-2024.11.16.mapping.split-0.template.json.gz,--output=https://log:pass@<es_node>:9201/index-creator-2024.11.16.mapping.split-0,--headers=null,--cert=null,--key=null,--pass=null,--ca=null,--tlsAuth=false,--input-cert=null,--input-key=null,--input-pass=null,--input-ca=null,--output-cert=null,--output-key=null,--output-pass=null,--output-ca=null,--httpAuthFile=null,--concurrency=1,--carryoverConcurrencyCount=true,--intervalCap=5,--concurrencyInterval=5000,--fsCompress=true,--compressionLevel=-1,--overwrite=false,--awsChain=false,--awsAccessKeyId=null,--awsSecretAccessKey=null,--awsIniFileProfile=null,--awsService=null,--awsRegion=null,--awsUrlRegex=null,--s3AccessKeyId=,--s3SecretAccessKey=,--s3Region=ru-moscow-1,--s3Endpoint=,--s3SSLEnabled=true,--s3ForcePathStyle=true,--s3Compress=true,--s3ServerSideEncryption=null,--s3SSEKMSKeyId=null,--s3ACL=null,--quiet=false,--prefix=,--suffix=,--scroll-with-post=false,--skip-existing=undefined,--params=null,--input-params=null,--output-params=null
Tue, 19 Nov 2024 08:41:29 GMT | starting dump
(node:18) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

NoSuchKey: The specified key does not exist.
    at Request.extractError (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/services/s3.js:711:35)
    at Request.callListeners (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'NoSuchKey',
  region: null,
  time: 2024-11-19T08:41:29.377Z,
  requestId: '000001934395780990C4E7CD7FA8C110',
  extendedRequestId: '32AAAQAAEAABAAAQAAEAABAAAQAAEAABCSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  cfId: undefined,
  statusCode: 404,
  retryable: false,
  retryDelay: 29.151077930727197
}

Node.js v20.17.0
Tue, 19 Nov 2024 08:41:29 GMT | indexing settings s3://<bucket>/<path>/index-creator-2024.11.16.mapping.split-0.settings.json.gz to https://log:pass@<es_node>:9201/index-creator-2024.11.16.mapping.split-0
Tue, 19 Nov 2024 08:41:29 GMT [debug] | fork: /usr/local/lib/node_modules/elasticdump/bin/elasticdump --type=settings,--input=s3://<bucket>/<path>/index-creator-2024.11.16.mapping.split-0.settings.json.gz,--output=https://log:pass@<es_node>:9201/index-creator-2024.11.16.mapping.split-0,--headers=null,--cert=null,--key=null,--pass=null,--ca=null,--tlsAuth=false,--input-cert=null,--input-key=null,--input-pass=null,--input-ca=null,--output-cert=null,--output-key=null,--output-pass=null,--output-ca=null,--httpAuthFile=null,--concurrency=1,--carryoverConcurrencyCount=true,--intervalCap=5,--concurrencyInterval=5000,--fsCompress=true,--compressionLevel=-1,--overwrite=false,--awsChain=false,--awsAccessKeyId=null,--awsSecretAccessKey=null,--awsIniFileProfile=null,--awsService=null,--awsRegion=null,--awsUrlRegex=null,--s3AccessKeyId=,--s3SecretAccessKey=,--s3Region=ru-moscow-1,--s3Endpoint=,--s3SSLEnabled=true,--s3ForcePathStyle=true,--s3Compress=true,--s3ServerSideEncryption=null,--s3SSEKMSKeyId=null,--s3ACL=null,--quiet=false,--prefix=,--suffix=,--scroll-with-post=false,--skip-existing=undefined,--params=null,--input-params=null,--output-params=null
Tue, 19 Nov 2024 08:41:29 GMT | starting dump
Tue, 19 Nov 2024 08:41:29 GMT | Working on index-creator-2024.11.16.settings.split-0
Tue, 19 Nov 2024 08:41:29 GMT | indexing template s3://<bucket>/<path>/index-creator-2024.11.16.settings.split-0.template.json.gz to https://log:pass@<es_node>:9201/index-creator-2024.11.16.settings.split-0
Tue, 19 Nov 2024 08:41:29 GMT [debug] | fork: /usr/local/lib/node_modules/elasticdump/bin/elasticdump --type=template,--input=s3://<bucket>/<path>/index-creator-2024.11.16.settings.split-0.template.json.gz,--output=https://log:pass@<es_node>:9201/index-creator-2024.11.16.settings.split-0,--headers=null,--cert=null,--key=null,--pass=null,--ca=null,--tlsAuth=false,--input-cert=null,--input-key=null,--input-pass=null,--input-ca=null,--output-cert=null,--output-key=null,--output-pass=null,--output-ca=null,--httpAuthFile=null,--concurrency=1,--carryoverConcurrencyCount=true,--intervalCap=5,--concurrencyInterval=5000,--fsCompress=true,--compressionLevel=-1,--overwrite=false,--awsChain=false,--awsAccessKeyId=null,--awsSecretAccessKey=null,--awsIniFileProfile=null,--awsService=null,--awsRegion=null,--awsUrlRegex=null,--s3AccessKeyId=,--s3SecretAccessKey=,--s3Region=ru-moscow-1,--s3Endpoint=,--s3SSLEnabled=true,--s3ForcePathStyle=true,--s3Compress=true,--s3ServerSideEncryption=null,--s3SSEKMSKeyId=null,--s3ACL=null,--quiet=false,--prefix=,--suffix=,--scroll-with-post=false,--skip-existing=undefined,--params=null,--input-params=null,--output-params=null
(node:29) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

NoSuchKey: The specified key does not exist.
    at Request.extractError (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/services/s3.js:711:35)
    at Request.callListeners (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'NoSuchKey',
  region: null,
  time: 2024-11-19T08:41:29.894Z,
  requestId: '0000019343957A129088B38B46F058B3',
  extendedRequestId: '32AAAQAAEAABAAAQAAEAABAAAQAAEAABCSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  cfId: undefined,
  statusCode: 404,
  retryable: false,
  retryDelay: 13.536494495830297
}
```

As I understand elasticdump searches for files without removing split and names type

**The index itself is created and data is written to it, but its name contains split-0**
_cat/indices
```green open index-creator-2024.11.16.split-0 bqznhPMyQL6JPRao-ugiZQ 1 1   6368 0   5.9mb  2.9mb```

**Comment by ferronrsmith** [comment]
This doesn't seem like you're using the latest version, but the problem you're having is related to an issue i forgot to fix.

Usually the file name matches the index name, but since the split+compression suffixes are now added, it forces 2 different name convention. one for the file being processed and the other for the index being processed. The problem is, this should only change if the output is ES. since you technically can use it for file->s3. 

You can submit a PR if you like, i am aware of the issue and will address it in the near future.

**Comment by ferronrsmith** [comment]
handled by https://github.com/elasticsearch-dump/elasticsearch-dump/pull/1067
