### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by amrfaissal** [elasticsearch-dump/elasticsearch-dump#413]
I was trying to push some data, which I dumped using `elasticdump`, back to ElasticSearch index, but I get this error:

```
/opt/node_modules/elasticdump/lib/parse-base-url.js:1
(function (exports, require, module, __filename, __dirname) { function parseBaseURL (_url, options = {}) {
                                                                                                   ^
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/cronos/deploy/node_modules/elasticdump/lib/transports/elasticsearch.js:3:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

This is the command I used to run to push data:
```
/opt/node_modules/elasticdump/bin/elasticdump --input=data.json --output=http://<ip_address>:9200/my_index
```

Stack:
```
ElasticDump version 3.3.8
ElasticSearch 5.x
NodeJS v4.2.6 
No dataset to share, sorry!
```

**Comment by amrfaissal** [comment]
I can confirm the command above works perfectly fine with `elasticdump version 3.3.7`.

**Comment by ferronrsmith** [comment]
node v8 and above. we dropped support for v4
