### ISSUE TITLE
[BUG] UnhandledPromiseRejectionWarning: Error: Pipeline failed

### ISSUE THREAD

**Issue by markmcnaughton** [elasticsearch-dump/elasticsearch-dump#695]
Please can you help me with this issue. I have exported files as JSON from an old Elasticsearch server into an S3 bucket and need to import them into a new Elasticsearch server managed by AWS. Some of the indexes import fine but several don't.

The details are as follows:

- ElasticDump version
6.28.0
- Elasticsearch version
7.4 (Amazon Elasticsearch)
- Node.js version
14.2.0
- NPM version
6.14.4

INPUT:
elasticdump --s3AccessKeyId XXX --s3SecretAccessKey XXX --awsAccessKeyId XXX --awsSecretAccessKey XXX --input s3://MY_BUCKET/MY_INDEX.json.split-0 --output=https://MY_ELASTICSEARCH_SERVER/MY_INDEX --limit 6000

OUTPUT:
Sun, 10 May 2020 13:00:39 GMT | starting dump
(node:1286) UnhandledPromiseRejectionWarning: Error: Pipeline failed
    at s3.setupGet (/usr/lib/node_modules/elasticdump/lib/transports/s3.js:85:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1286) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1286) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Let me know if I can provide any further information.

**Comment by ferronrsmith** [comment]
The pipeline failed when trying to access s3. I've pushed `v6.28.1` that will inspect the error thrown int he pipeline

**Comment by markmcnaughton** [comment]
Thanks for such a quick response Ferron,

looks like a 403 forbidden error. I'll try and figure out why.

`Mon, 11 May 2020 05:47:49 GMT | starting dump
(node:26466) UnhandledPromiseRejectionWarning: Error: {
  msg: 'Pipeline failed',
  err: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
      at Request.extractError (/usr/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/services/s3.js:835:35)
      at Request.callListeners (/usr/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/usr/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/usr/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/request.js:683:14)
      at Request.transition (/usr/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/usr/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /usr/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/usr/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/usr/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/request.js:685:12)
      at Request.callListeners (/usr/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
    code: 'SignatureDoesNotMatch',
    region: null,
    time: 2020-05-11T05:47:49.337Z,
    requestId: '46A951EE1B91XXX',
    extendedRequestId: 'XXXXXX',
    cfId: undefined,
    statusCode: 403,
    retryable: false,
    retryDelay: 105.53401027372513
  }
}
    at s3.setupGet (/usr/lib/node_modules/elasticdump/lib/transports/s3.js:87:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26466) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26466) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by markmcnaughton** [comment]
If someone else comes across this, I regenerated my IAM access key. I made sure that it didn't have any symbols such as / or +. After doing this, it worked, not sure of the cause. Perhaps it's an escaping issue.

**Comment by ferronrsmith** [comment]
Thanks, I'll tag it with the "COOKBOOK" label

**Comment by i4never** [comment]
> 

Save my day.
