### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "timeout" argument must be of type number. Received null

### ISSUE THREAD

**Issue by ghl1024** [elasticsearch-dump/elasticsearch-dump#698]
# Backup index data to a file
```
[root@aliyun ~]$ elasticdump --input=http://elastic:elasticsearch@143.45.21.145:9200/test --output=/root/query.json --type=data
Wed, 20 May 2020 01:44:19 GMT | starting dump
internal/validators.js:126
    throw new ERR_INVALID_ARG_TYPE(name, 'number', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "timeout" argument must be of type number. Received null
    at validateNumber (internal/validators.js:126:11)
    at getTimerDuration (internal/timers.js:376:3)
    at new ClientRequest (_http_client.js:170:20)
    at Object.request (http.js:46:10)
    at Request.start (/usr/lib/node_modules/request/index.js:604:30)
    at Request.end (/usr/lib/node_modules/request/index.js:1211:28)
    at /usr/lib/node_modules/request/index.js:436:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
# query doc
```
[root@aliyun ~]$ curl http://elastic:elasticsearch@143.45.21.145.6:9200/test/_doc/1
{"_index":"test","_type":"_doc","_id":"1","_version":1,"_seq_no":0,"_primary_term":1,"found":true,"_source":{
  "name":"hayden",
  "age":25
}
}
```
# elasticdump version is 6.28
```
[root@aliyun ~]$elasticdump --help
elasticdump: Import and export tools for elasticsearch
version: 6.28.3

Usage: elasticdump --input SOURCE --output DESTINATION [OPTIONS]

--input
                    Source location (required)
......
```
# elasticsearch version 7.2.0
```
[root@aliyun ~]$ curl http://elastic:elasticsearch@143.45.21.145:9200
{
  "name" : "master",
  "cluster_name" : "Hayden",
  "cluster_uuid" : "jTTjDOHVQnOq7vGDEXdQTQ",
  "version" : {
    "number" : "7.2.0",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "508c38a",
    "build_date" : "2019-06-20T15:54:18.811730Z",
    "build_snapshot" : false,
    "lucene_version" : "8.0.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```
# npm version 6.14.4
```
[root@aliyun ~]$ npm -v
6.14.4
[root@aliyun ~]$ 
```
# node version 14.2.0
```
[root@aliyun ~]$ node -v
v14.2.0
[root@aliyun ~]$ 
```
# OS version CentOS7.3
```
[root@aliyun ~]$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
[root@aliyun ~]$ cat /
```

**Comment by ferronrsmith** [comment]
try using the docker version if you're still getting issues, but from the error above it doesn't seem like it's directly related to the library.
