### ISSUE TITLE
Restoring index data on non-standard ES install

### ISSUE THREAD

**Issue by luigikitten** [elasticsearch-dump/elasticsearch-dump#709]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version : from Docker image
- Elasticsearch version : 7.7.1
- Node.js version *(note that nodejs v8+ is required for this tool) - from Docker image
- Full command you are having issue with (with inputs and outputs) - see below
- A data-set you can share publicly which reproduces the problem - see below

**Describe the bug**
Hi,
   i am trying to restore data elastic-dump via docker and I am not able to restore data. I have a non standard install, i.e. my elastic indexes are located in something like
http://myprettydns:443/qa/myindex    (served via Apache)

--- how I create a backup:
I am using the following script (adapted from the docker examples):
```
	docker run --rm -ti -e  NODE_TLS_REJECT_UNAUTHORIZED=0 -v $(pwd)/data:/data:Z elasticdump/elasticsearch-dump elasticdump \
	  --input=https://${ELASTICSEARCH_USER}:${ELASTICSEARCH_PASSWORD}@${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}/${ELASTICSEARCH_ENV} \
	  --input-index=${ELASTICSEARCH_INDEX} --limit 100000 \
 	 --output=/data/${ENV}_${ELASTICSEARCH_INDEX}_data.json.gz \
	  --type=data --fsCompress 
```
this creates a file with many lines like:
```
{"_index":"myindex","_type":"_doc","_id":"ID000001","_score":1,"_source":{...............}" }
```

--- how I try to restore
Now I would like to restore to the same server: I am trying the following:
```
	zcat $FILE |\
	 docker run --rm  -i -e  NODE_TLS_REJECT_UNAUTHORIZED=0 -v $(pwd)/data:/data:Z elasticdump/elasticsearch-dump elasticdump \
	  --output=https://${ELASTICSEARCH_USER}:${ELASTICSEARCH_PASSWORD}@${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}/${ELASTICSEARCH_ENV}/${ELASTICSEARCH_INDEX} \
 	 --input=$  --limit 1000 --type=data 
```
getting the error:
```
Thu, 18 Jun 2020 08:44:03 GMT | starting dump
Thu, 18 Jun 2020 08:44:03 GMT | got 1000 objects from source file (offset: 0)
(node:1) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(node:1) UnhandledPromiseRejectionWarning: Error: failed to parse json (message: "Unexpected token < in JSON at position 0") - source: "<html><body><h1>It works!</h1></body></html>\n"
    at Object.parse (/usr/local/lib/node_modules/elasticdump/lib/jsonparser.js:45:11)
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/lib/transports/elasticsearch.js:120:29)
    at Request._callback (/usr/local/lib/node_modules/elasticdump/node_modules/lodash/lodash.js:10050:25)
    at Request.requestRetryReply [as reply] (/usr/local/lib/node_modules/elasticdump/node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/requestretry/index.js:146:10)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
read unix @->/var/run/docker.sock: read: connection reset by peer
```

same error removing the `/${ELASTICSEARCH_INDEX}` from `--output` 

changing the command to:
```
  zcat $FILE |\
    docker run --rm  -i -e  NODE_TLS_REJECT_UNAUTHORIZED=0 -v $(pwd)/data:/data:Z elasticdump/elasticsearch-dump elasticdump \
    --output=https://${ELASTICSEARCH_USER}:${ELASTICSEARCH_PASSWORD}@${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}/${ELASTICSEARCH_ENV} \
    --input=$  --limit 1000 \
    --output-index=${ELASTICSEARCH_INDEX} \
    --type=data 
```
I get the error:
```
Thu, 18 Jun 2020 08:46:42 GMT | starting dump
Thu, 18 Jun 2020 08:46:43 GMT | got 1000 objects from source file (offset: 0)
(node:1) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
Thu, 18 Jun 2020 08:46:43 GMT | Error Emitted => {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"explicit index in bulk is not allowed"}],"type":"illegal_argument_exception","reason":"explicit index in bulk is not allowed"},"status":400}
Thu, 18 Jun 2020 08:46:43 GMT | Error Emitted => {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"explicit index in bulk is not allowed"}],"type":"illegal_argument_exception","reason":"explicit index in bulk is not allowed"},"status":400}
Thu, 18 Jun 2020 08:46:43 GMT | Total Writes: 0
Thu, 18 Jun 2020 08:46:43 GMT | dump ended with error (get phase) => BAD_REQUEST: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"explicit index in bulk is not allowed"}],"type":"illegal_argument_exception","reason":"explicit index in bulk is not allowed"},"status":400}
read unix @->/var/run/docker.sock: read: connection reset by peer
```

How can I restore this dump?

Any help would be appreciated, many thanks!

**Comment by ferronrsmith** [comment]
To help there is a few questions that's needed.

1. How do you normally perform a search against the API (via curl). What's the endpoint?
1. What's the scroll endpoint.

Sounds like your installation doesn't allow bulk indexing (This is an action control issue)
```json
{
	"error": {
		"root_cause": [{
			"type": "illegal_argument_exception",
			"reason": "explicit index in bulk is not allowed"
		}],
		"type": "illegal_argument_exception",
		"reason": "explicit index in bulk is not allowed"
	},
	"status": 400
}
```

The first issue was because the url supplied was incorrect. It's returning html instead of json

```html
<html><body><h1>It works!</h1></body></html>
```



My guess you need to speak with whomever configured the server

Access control info : https://www.elastic.co/guide/en/elasticsearch/reference/7.x/url-access-control.html
