### ISSUE TITLE
[BUG] ReferenceError: URL is not defined

### ISSUE THREAD

**Issue by buzzdeee** [elasticsearch-dump/elasticsearch-dump#718]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: 6.31.4
- Elasticsearch version: 7.6.2
- Node.js version: 8.10.0

This is on ubuntu 18.04.4

**Describe the bug**
when using --httpAuthFile parameter, elasticdump ends with backtrace.

**To Reproduce**
I've security enabled, so have to use HTTPS and authentication, so have to run elasticdump alike:
```
NODE_TLS_REJECT_UNAUTHORIZED=0 elasticdump --input=https://127.0.0.1:9200/.kibana --httpAuthFile=./auth --output=/tmp/.kibana.json
/usr/local/lib/node_modules/elasticdump/lib/add-auth.js:10
  const urlObject = new URL(urlToAddAuth)
                    ^

ReferenceError: URL is not defined
    at addAuth (/usr/local/lib/node_modules/elasticdump/lib/add-auth.js:10:21)
    at getIo (/usr/local/lib/node_modules/elasticdump/lib/ioHelper.js:12:37)
    at new ElasticDump (/usr/local/lib/node_modules/elasticdump/elasticdump.js:29:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/elasticdump/bin/elasticdump:113:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```

**Current behavior**
instead of dumping the index, it elasticdump crashes.

**Expected behavior**
it should just dump the index.

**Additional context**
This seems to be related to nodejs version < 10.

There seems to be a workaround as explained here:
https://stackoverflow.com/questions/52566578/url-is-not-defined-in-node-js

tweaking /usr/local/lib/node_modules/elasticdump/lib/add-auth.js to add the line:

```
var URL = require('url').URL;
```

just before the module.exports = addAuth line,
fixes the issue for me. However, I've no idea if that would break for nodejs 10.x versions.

**Comment by ferronrsmith** [comment]
aded a backward compatibility patch for this.
