### ISSUE TITLE
[BUG] Error: EACCES: permission denied, open

### ISSUE THREAD

**Issue by kaykhancheckpoint** [elasticsearch-dump/elasticsearch-dump#768]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version
6.65.3
- Elasticsearch version
latest
- Node.js version *(note that nodejs v10+ is required for this tool)*
v12.18.3
- Full command you are having issue with (with inputs and outputs)
```
elasticdump \
  --input=http://<redacted>:<redacted>@elasticsearch.<redacted>.com/<redacted> \
  --output=/search_index.json \
  --type=mapping
```
- A data-set you can share publicly which reproduces the problem
n/a

**Describe the bug**
Trying to export from remote to local json file when i get the error permission denied.

**To Reproduce**
1. npm install -g elasticdump
2. run full comand above

**Current behavior**

Getting permission denied error

> Fri, 12 Feb 2021 15:02:59 GMT | starting dump
> Fri, 12 Feb 2021 15:02:59 GMT | got 1 objects from source elasticsearch (offset: 0)
> Fri, 12 Feb 2021 15:02:59 GMT | sent 1 objects to destination file, wrote 1
> events.js:292
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: EACCES: permission denied, open '/search_index.json'
> Emitted 'error' event on WriteStream instance at:
>     at errorOrDestroy (internal/streams/destroy.js:108:12)
>     at WriteStream.onerror (_stream_readable.js:752:7)
>     at WriteStream.emit (events.js:315:20)
>     at WriteStream.EventEmitter.emit (domain.js:483:12)
>     at internal/fs/streams.js:361:12
>     at FSReqCallback.oncomplete (fs.js:156:23) {
>   errno: -13,
>   code: 'EACCES',
>   syscall: 'open',
>   path: '/search_index.json'
> }

**Expected behavior**
Should export to json file.

**Comment by kaykhancheckpoint** [comment]
removing the leading "/" in the output flag worked ```--output=/search_index.json \``` should be ```--output=search_index.json \```
