### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by abreudenis83** [elasticsearch-dump/elasticsearch-dump#776]
### Error:
```
/usr/lib/node_modules/elasticdump/lib/processor.js:40
  async _loop (limit, offset, totalWrites) {
        ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/elasticdump/elasticdump.js:3:28)
```

### Versions:
```
# npm version                                                                                                                                                                      [18:41:46]
{ elasticdump: '6.66.1',
  npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.8.0',
  icu: '50.1.2',
  modules: '48',
  napi: '3',
  node: '6.17.1',
  openssl: '1.0.2k-fips',
  uv: '1.41.0',
  v8: '5.1.281.111',
  zlib: '1.2.7' }
```

**Comment by ferronrsmith** [comment]
Node v10 or higher
