### ISSUE TITLE
Cannot find module '/root/node_modules/aws-sdk/scripts/check-node-version.js'

### ISSUE THREAD

**Issue by stevebanik** [elasticsearch-dump/elasticsearch-dump#844]
```
[root@es3 ~]# npm install elasticdump
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated s3signed@0.1.0: This module is no longer maintained. It is provided as is.
> aws-sdk@2.920.0 postinstall /root/node_modules/aws-sdk
> node scripts/check-node-version.js
internal/modules/cjs/loader.js:638
    throw err;
    ^
Error: Cannot find module '/root/node_modules/aws-sdk/scripts/check-node-version.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aws-sdk@2.920.0 postinstall: `node scripts/check-node-version.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aws-sdk@2.920.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-22T19_28_09_935Z-debug.log
```

**Comment by stevebanik** [comment]
```
[root@es3 ~]# uname -a
Linux es3 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Tue Nov 16 14:42:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ferronrsmith** [comment]
This needs more information. Don't know the node version, it needs to be v10 or higher

**Comment by ferronrsmith** [comment]
Seems to be related to https://github.com/aws/aws-sdk-js/issues/3763


As a workaround, setting the following environment variable seems to fix it:

```
NPM_CONFIG_UNSAFE_PERM=true
```

**Comment by BigData-YC** [comment]
how to dealwith?

**Comment by BigData-YC** [comment]
[root@chanke-bd-test-node-master1JwPe node]# node -v
v16.14.0
[root@chanke-bd-test-node-master1JwPe node]# npm -v
8.5.1
