### ISSUE TITLE
[BUG] ERR_INVALID_ARG_TYPE when using multielasticdump to load from s3

### ISSUE THREAD

**Issue by zweger** [elasticsearch-dump/elasticsearch-dump#849]
- ElasticDump version: 6.79.0
- Elasticsearch version: N/A
- Node.js version: 12.16.2
- Full command you are having issue with: `multielasticdump --direction=load --limit 10000 --match='^.*$' --input=s3://bucket/dump --output=https://admin:password@hostname --awsChain=true --debug`
- A data-set you can share publicly which reproduces the problem: N/A

**Describe the bug**
I get the following error when running the above command. Note that the placeholder bucket name, elastic hostname etc. in the command don't matter. The error occurs prior to any network timeout, permission check, etc.

```
internal/validators.js:117
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Url.parse (url.js:159:3)
    at urlParse (url.js:154:13)
    at Object.fromUrl (/deploy/node-v12.16.2-linux-x64/lib/node_modules/elasticdump/node_modules/s3urls/index.js:5:15)
    at listFiles (/deploy/node-v12.16.2-linux-x64/lib/node_modules/elasticdump/bin/multielasticdump:229:44)
    at Object.<anonymous> (/deploy/node-v12.16.2-linux-x64/lib/node_modules/elasticdump/bin/multielasticdump:327:3)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Additional context**
I'm not certain but I suspect the problem is this line in multielasticdump: https://github.com/elasticsearch-dump/elasticsearch-dump/blob/fc8a76d8bfa81536c92398f870ca44917f9cddd1/bin/multielasticdump#L229. 

`this.file` looks like it should be replaced with `dir`.

**Comment by ferronrsmith** [comment]
fixed by 29d19cc307a9c46b97614ecab86c7ed773db0006, released in https://github.com/elasticsearch-dump/elasticsearch-dump/releases/tag/v6.79.3
