### ISSUE TITLE
[BUG] AWS Open Search SSO Auth

### ISSUE THREAD

**Issue by moophlo** [elasticsearch-dump/elasticsearch-dump#888]
**Context**
- ElasticDump version 6.82.3
- Elasticsearch version input 7.16.1
- Elasticsearch version output 7.10.2
- Node.js version - using docker version with latest TAG
- Full command you are having issue with (with inputs and outputs):

```docker run --net=host --rm -ti elasticdump/elasticsearch-dump --input=http://localhost:9200/tmp_byond_tr_contabile --output=https://pm-aws-test:<password>@<URI-pubblic-endpoint>/tmp_byond_tr_contabile --type=data```

NOTE: Source is not authenticated and the target is the managed version of AWS Opensearch with SAML SSO with Keycloak

**Describe the bug**
It seems like is not authenticating on the target and it stops on Keycloak

**Current behavior**
```Tue, 28 Jun 2022 11:46:21 GMT | starting dump
Tue, 28 Jun 2022 11:46:21 GMT | got 0 objects from source elasticsearch (offset: 0)
Tue, 28 Jun 2022 11:46:21 GMT | Total Writes: 0
Tue, 28 Jun 2022 11:46:21 GMT | dump complete
(node:1) UnhandledPromiseRejectionWarning: Error: failed to parse json (message: "Unexpected token < in JSON at position 0") - source: "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transiti
onal//EN\"  \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" class=\"login-pf\">\n\n<head>\n    <meta charset=\"utf-8\">\n    <meta 
http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n    <meta name=\"robots\" content=\"noindex, nofollow\">\n\n            <meta name=\"viewport\" content=\"width=device-wi
dth,initial-scale=1\"/>\n    <title>Log in to Company Intranet</title>\n    <link rel=\"icon\" href=\"/auth/resources/fs8xo/login/keycloak/img/favicon.ico\" />\n            <link href=\"/auth
/resources/fs8xo/login/keycloak/node_modules/patternfly/dist/css/patternfly.min.css\" rel=\"stylesheet\" />\n            <link href=\"/auth/resources/fs8xo/login/keycloak/node_modules/patter
nfly/dist/css/patternfly-additions.min.css\" rel=\"stylesheet\" />\n            <link href=\"/auth/resources/fs8xo/login/keycloak/lib/zocial/zocial.css\" rel=\"stylesheet\" />\n            <
link href=\"/auth/resources/fs8xo/login/keycloak/css/login.css\" rel=\"stylesheet\" />\n</head>\n\n<body class=\"\">\n  <div class=\"login-pf-page\">\n    <div id=\"kc-header\" class=\"login
-pf-page-header\">\n      <div id=\"kc-header-wrapper\" class=\"\">Intranet</div>\n    </div>\n    <div class=\"card-pf \">\n      <header class=\"login-pf-header\">\n                <h1 id=
\"kc-page-title\">        Log In\n\n</h1>\n      </header>\n      <div id=\"kc-content\">\n        <div id=\"kc-content-wrapper\">\n\n\n    <div id=\"kc-form\" >\n      <div id=\"kc-form-wra
pper\" >\n            <form id=\"kc-form-login\" onsubmit=\"login.disabled = true; return true;\" action=\"https://keycloak.blablabla.it/auth/realms/blablabla/login-actions/authen
ticate?session_code=S6ng0BHUMTLTfHJm0MS077zZjPnqeCr_j0pxoUKtBeM&amp;execution=0fb9df51-de77-4115-9c0d-b7e5b19ef3d0&amp;client_id=https%3A%2F%2Fkibana-byond.wlms-ita.com&amp;tab_id=vixTl_AjYX
Q\" method=\"post\">\n                <div class=\"form-group\">\n                    <label for=\"username\" class=\"control-label\">Username or email</label>\n\n                        <in
put tabindex=\"1\" id=\"username\" class=\"form-control\" name=\"username\" value=\"\"  type=\"text\" autofocus autocomplete=\"off\" />\n                </div>\n\n                <div class=
\"form-group\">\n                    <label for=\"password\" class=\"control-label\">Password</label>\n                    <input tabindex=\"2\" id=\"password\" class=\"form-control\" name=\
"password\" type=\"password\" autocomplete=\"off\" />\n                </div>\n\n                <div class=\"form-group login-pf-settings\">\n                    <div id=\"kc-form-options\"
>\n                        </div>\n                        <div class=\"\">\n                        </div>\n\n                  </div>\n\n                  <div id=\"kc-form-buttons\" class
=\"form-group\">\n                      <input type=\"hidden\" id=\"id-hidden-input\" name=\"credentialId\" />\n                      <input tabindex=\"4\" class=\"btn btn-primary btn-block 
btn-lg\" name=\"login\" id=\"kc-login\" type=\"submit\" value=\"Log In\"/>\n                  </div>\n            </form>\n        </div>\n      </div>\n\n\n\n        </div>\n      </div>\n\
n    </div>\n  </div>\n</body>\n</html>\n"
    at Object.parse (/usr/local/lib/node_modules/elasticdump/lib/jsonparser.js:48:11)
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/lib/transports/__es__/_base.js:41:31)
    at Request._callback (/usr/local/lib/node_modules/elasticdump/node_modules/lodash/lodash.js:10118:25)
    at Request.requestRetryReply [as reply] (/usr/local/lib/node_modules/elasticdump/node_modules/requestretry/index.js:150:19)
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/requestretry/index.js:191:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise 
which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_u
nhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero 
exit code.```

**Expected behavior**
Expected to start the dump&restore from input to output.


**Additional context**
```root@host:~# curl -X GET https://pm-aws-test:<password>@<URI-pubblic-endpoint>/_cluster/health?pretty
{
  "cluster_name" : "673983127293:byond01-ph-ec1",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 6,
  "number_of_data_nodes" : 3,
  "discovered_master" : true,
  "active_primary_shards" : 14,
  "active_shards" : 29,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}```

**Comment by ferronrsmith** [comment]
Can you bump to the latest version ? 6.84.1

**Comment by moophlo** [comment]
Sorry but the docker version is not always using the latest version available?

**Comment by ferronrsmith** [comment]
<img width="595" alt="Screen Shot 2022-06-29 at 3 17 43 PM" src="https://user-images.githubusercontent.com/159764/176518148-4a11b267-6ee2-4276-a38f-324a7013d1b0.png">

**Comment by ferronrsmith** [comment]
did you encode the password ?

**Comment by moophlo** [comment]
Yes, tried with and without encode ... but anyway I'm using a password without special characters. Tried using the curl User-Agent but no luck.It seems like with curl it does bypass keycloak SAML auth and goes straight to local user but with elasticsearch-dump command it feels into keycloak login page and stops there of course.

**Comment by ferronrsmith** [comment]
That's strange ... It would be interesting to debug, but I don't have access to your environment. I suspect something is modifying the url and causing it to redirect to the login page

**Comment by ferronrsmith** [comment]
Try enabling the `--debug``

**Comment by ferronrsmith** [comment]
This requires a little more debugging, but I'm afraid I can't since it's in your environment. I suspect that the URL being passed it causing issues, but I can't confirm without testing

**Comment by kirajen-lego** [comment]
Hi - I am currently facing the same problem. Did you ever figure it out @moophlo ?
