### ISSUE TITLE
[FEATURE] Accept-Encoding:gzip and Content-Encoding:gzip

### ISSUE THREAD

**Issue by mfelician** [elasticsearch-dump/elasticsearch-dump#920]
I'm struggling with lower-than-expected data migration speed between ES clusters.

I think one of the reasons of the poor performance is actually the network bandwidth. In my case as I'm dealing with huge documents with a limited upload speed. I noticed that all the data goes deflated from source ES to elasticdump (and possibly from elasticdump to target ES too.) 
I think the http communication should be performed with gzip compression by using Accept-Encoding:gzip

I've tried adding Accept-Encoding:gzip request headers via the --headers attribute but all I could find was that the binary response was not parseable by the json parser of elasticdump.

I think gzip compression should be the default behaviour for all scroll and _bulk requests and it should be possible to turn off via a parameter.

**Comment by ferronrsmith** [comment]
You can already pass customs headers

```
--headers="{\"Accept-Encoding\":\"gzip\",\"Content-Encoding\":\"gzip\"}"
```

**Comment by mfelician** [comment]
Yes, we can add those headers, but elasticdump cannot handle the compressed response from ES:

`
elasticdump --version
6.88.0


elasticdump -input=http://some_old_index/src_index --output=https://some_new_index/target_index --headers="{\"Accept-Encoding\":\"gzip\",\"Content-Encoding\":\"gzip\"}"
Tue, 04 Oct 2022 22:54:51 GMT | starting dump
(node:665) UnhandledPromiseRejectionWarning: Error: failed to parse json (message: "Unexpected token  in JSON at position 0") - source: "\u001f�\b\u0000\u0000\u0000\u0000\u0000\u0002�T�MO�0\f���\u0015Qbinary..removed...manually\u0000\u0003�o�q\u0001\u0000\u0000"
    at Object.parse (/usr/local/lib/node_modules/elasticdump/lib/jsonparser.js:48:11)
    at Request.baseRequest (/usr/local/lib/node_modules/elasticdump/lib/transports/__es__/_base.js:41:31)
    at Request._callback (/usr/local/lib/node_modules/elasticdump/node_modules/lodash/lodash.js:10118:25)
    at Request.requestRetryReply [as reply] (/usr/local/lib/node_modules/elasticdump/node_modules/requestretry/index.js:151:19)
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/requestretry/index.js:192:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:665) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:665) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by ferronrsmith** [comment]
I've added an `--esCompress` flag for this (release 6.89.0)

closed by : https://github.com/elasticsearch-dump/elasticsearch-dump/commit/a5df616f5867eff06e1ce73ccfa03258baf92c0a

**Comment by mfelician** [comment]
I'll experiment more with this in local debug but it looks like the outgoing request is still not compressed. So the outgoing _bulk API call is still several megabytes large. I am not sure how to make the clientrequest library to make a compressed outgoing request.

**Comment by ferronrsmith** [comment]
The underlining library doesn't support gzip on outgoing req, hence the reason why this feature is not available. I could add it, but it will require effort.

**Comment by ferronrsmith** [comment]
It's actually not that hard to add after looking into it. I'll test it later before pushing a release

**Comment by mfelician** [comment]
I've just tried to hack in manual gzip compression, but I just cannot get it right with the request library. The best I could get was BAD_REQUEST: 400 Not in GZIP format. I'm not sure what I was missing. 

```
    var zlib = require('zlib')
    var input = new Buffer(payload.body, 'utf8')  
    payload.body = zlib.deflateSync(input)    
    payload.headers["Content-Encoding"] = "gzip"
```

**Comment by mfelician** [comment]
Finally, I've got it working. I've just learned that deflate is not the same as gzip.

All I did was hack in the below 3 lines into _data.js

```
    var zlib = require('zlib')
    payload.body = zlib.gzipSync(payload.body)        
    payload.headers["Content-Encoding"] = "gzip"
```

Result:
![image](https://user-images.githubusercontent.com/7103608/194063164-3e1c5674-93be-4788-ae88-0c4282d3a894.png)

This looks to be almost a 2x speed gain.

**Comment by mfelician** [comment]
Off topic:
Hmm, I'm sorry, what do you mean? Is there a potential to use concurrency here for a single index? Looking at the code I cannot see how this could be (easily) concurrent. I wish I could use now like 10 concurrent threads since the network is no longer the main concern. ;-)
