### ISSUE TITLE
[BUG] Typo in bulkAction argv parser

### ISSUE THREAD

**Issue by ianling** [elasticsearch-dump/elasticsearch-dump#938]
**Describe the bug**
https://github.com/elasticsearch-dump/elasticsearch-dump/blob/master/lib/argv.js#L37

The word "create" in the regex matcher has a right curly brace after it: `|create}`

**To Reproduce**
Run elasticdump with `--bulkAction=create`

**Current behavior**
It doesn't work

**Expected behavior**
It works

**Additional context**
```
/usr/local/lib/node_modules/elasticdump/lib/argv.js:38
        throw Error(`Unsupported action detected in bulkAction property : ${this.options[i]}`)
        ^

Error: Unsupported action detected in bulkAction property : create
    at argv.parse (/usr/local/lib/node_modules/elasticdump/lib/argv.js:38:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/elasticdump/bin/elasticdump:145:6)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

Removing the right curly brace after `create` fixed the issue when I tried it locally.

**Comment by ferronrsmith** [comment]
fixed https://github.com/elasticsearch-dump/elasticsearch-dump/commit/d863e903dd41e47e7a4533db92957166cd3479e2
