### ISSUE TITLE
deleteIndexes does not sign requests

### ISSUE THREAD

**Issue by aviau** [elasticsearch-dump/elasticsearch-dump#939]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: v6.94.1
- Elasticsearch version: OpenSearch 2.3
- Node.js version: v14.21.1

**Describe the bug**

When I run multielasticdump with `--direction=load` and `--delete`, I get the following:

```
Tue, 03 Jan 2023 21:18:16 GMT | Working on account
Tue, 03 Jan 2023 21:18:16 GMT | indexing settings s3://redacted/aa.json to https://redacted:443/account
Tue, 03 Jan 2023 21:18:17 GMT [debug] | DELETE redacted_1,redacted_2 -> 401 Unauthorized
undefined:1
Unauthorized
^

SyntaxError: Unexpected token U in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/local/lib/node_modules/elasticdump/bin/multielasticdump:285:21)
    at Request.self.callback (/usr/local/lib/node_modules/elasticdump/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.emit (domain.js:475:12)
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:400:28)
    at Request.emit (domain.js:475:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
```

The expected behaviour would be that even this request is signed. Looking at the code it looks like it only supports http basic auth.

**Comment by ferronrsmith** [comment]
There isn't enough information to go one here. `--delete` only works from ES -> ES

**Comment by aviau** [comment]
This is the full command that I use:
```
              multielasticdump
              --input=s3://flared-elasticsearch-dump/daily
              --output=${ES_URL}
              --s3AccessKeyId=${AWS_ACCESS_KEY_ID}
              --s3SecretAccessKey=${AWS_SECRET_ACCESS_KEY}
              --s3Compress=true
              --awsChain
              --includeType='data,mapping,analyzer,alias,settings'
              --direction=load
              --delete
```

What do you mean by es-es? We have been restoring indexes from S3 with --delete.

**Comment by ferronrsmith** [comment]
I thought you meant with elasticdump, now this makes sense. That's for the contribution. It's important to give as much information as possible

**Comment by ferronrsmith** [comment]
looks good, i'll merge it. Seems you even fixed a possible race-condition 👍🏾

**Comment by ferronrsmith** [comment]
Your changes have been merged and released, thanks.
