### ISSUE TITLE
[BUG] (node:48691) UnhandledPromiseRejectionWarning: RangeError: Invalid string length

### ISSUE THREAD

**Issue by pt-arvind** [elasticsearch-dump/elasticsearch-dump#943]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: 6.96.0
- Elasticsearch version: 7.16.1
- Node.js version: v14.18.0
- Full command you are having issue with (with inputs and outputs)
```
NODE_OPTIONS="--max_old_space_size=700000" elasticdump \
  --input=http://<my es server>:9200/<my es index> \
  --output=./<my es index>.json \
  --fileSize=3gb \
  --limit=100 \
  --retryAttempts=5 \
  --noRefresh 
```

- A data-set you can share publicly which reproduces the problem: unfortunately, cannot share

**Describe the bug**
when trying to elasticdump an index with very large docs (some json docs are close to 2gigs) the program fails with the following error:

```
Thu, 05 Jan 2023 17:28:01 GMT | got 100 objects from source elasticsearch (offset: 383900)                                                     
Thu, 05 Jan 2023 17:28:02 GMT | sent 100 objects to destination file, wrote 100
(node:48691) UnhandledPromiseRejectionWarning: RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at Object.stringify (/usr/local/lib/node_modules/elasticdump/lib/jsonparser.js:56:10)
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/lib/transports/__es__/_helpers.js:87:55)
    at Request._callback (/usr/local/lib/node_modules/elasticdump/node_modules/lodash/lodash.js:10118:25)                                      [1831/1861]
    at Request.requestRetryReply [as reply] (/usr/local/lib/node_modules/elasticdump/node_modules/requestretry/index.js:151:19)
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/requestretry/index.js:192:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:48691) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a
 catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:48691) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

essentially the problem is here: https://github.com/elasticsearch-dump/elasticsearch-dump/blob/master/lib/transports/__es__/_helpers.js#L87

it looks like the JSON stringify function here does not use buffers . Additionally, my machine has more than 1TB memory and the node memory limits have been set as shown in the command.

**Comment by ferronrsmith** [comment]
The problem is node as an enforced upper-bound for string length. I'll add a check for this.

**Comment by ferronrsmith** [comment]
I sent a PR with a fix. Test and let me know if this works for you.

**Comment by pt-arvind** [comment]
testing, it takes some hours to get to that point but I will let you know, thank you so much!

**Comment by pt-arvind** [comment]
```bash
─
Thu, 05 Jan 2023 20:45:04 GMT | starting dump
(node:51563) UnhandledPromiseRejectionWarning: TypeError: scrollResultSet is not a function
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/lib/transports/__es__/_data.js:87:11)
    at Request._callback (/usr/local/lib/node_modules/elasticdump/node_modules/lodash/lodash.js:10118:25)
    at Request.requestRetryReply [as reply] (/usr/local/lib/node_modules/elasticdump/node_modules/requestretry/index.js:151:19)
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/requestretry/index.js:192:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:51563) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:51563) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by pt-arvind** [comment]
```
(node:51563) UnhandledPromiseRejectionWarning: TypeError: scrollResultSet is not a function
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/lib/transports/__es__/_data.js:87:11)
    at Request._callback (/usr/local/lib/node_modules/elasticdump/node_modules/lodash/lodash.js:10118:25)
    at Request.requestRetryReply [as reply] (/usr/local/lib/node_modules/elasticdump/node_modules/requestretry/index.js:151:19)
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/requestretry/index.js:192:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:51563) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:51563) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I just commented out the emit line on my current code base and that seems to be OK

**Comment by pt-arvind** [comment]
hmm that didnt work either when I ran it, sadly, the error was just somewhere else, though it explicitly showed the max string error

```
buffer.js:821
    return this.utf8Slice(start, end);

Error: Cannot create a string longer than 0x1fffffe8 characters
    at Buffer.toString (buffer.js:821:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/request/request.js:1128:39)
    at Request.emit (events.js:400:28)
    at Request.emit (domain.js:475:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ERR_STRING_TOO_LONG'
```

I am just gonna work around this by trying to query differently
